version: '3'

services:
  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "sti_llm_mongo"
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
      - ~/my-data:/data/my-data

  jupyter:
    image: jupyter/datascience-notebook
    container_name: sti_llm_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      RESTARTABLE: "yes"
      GRANT_SUDO: "yes"
      JUPYTER_TOKEN: "stillm"
    env_file:
      - ./.env  
    ports:
      - "${MY_JUPYTER_PORT}:8888"
    restart: always
    volumes:
      - ./work:/home/jovyan/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
